app/urls.py
from django.conf.urls import url
from app.views import *

# # apis
# urlpatterns = [
#     url(r'^api/customers$', CustomerListAPIView.as_view({'get': 'list'})),
#     url(r'^api/customer/(?P<pk>[0-9]+)$', CustomerAPIView.as_view()),
#     url(r'^api/login$', CustomerLoginAPIView.as_view()),
#     url(r'^api/get-customer-name$', CustomerDetailsAPIView.as_view()),
# ]

# django web views
urlpatterns = [
    url(r'^$', CustomerDashboardView.as_view(), name="customer_dashboard"),
    url(r'order$', CustomerOrderView.as_view(), name="customer_order"),
    url(r'order-review/(?P<pk>\d+)/$', OrderReviewView.as_view(), name="order_review"),
    url(r'order-list/$', CustomerOrderListView.as_view(), name="list_orders"),
    url(r'update-status$', UpdateOrderStatus.as_view(), name="update_status"),
    url(r'provider-list/(?P<request_id>\d+)/$', ProviderListView.as_view(), name="provider_list"),

    # Provider views

    url(r'provider/$', ProviderDashboardView.as_view(), name="provider_dashboard"),
    url(r'provider/history/$', ProviderHistoryView.as_view(), name="provider_histor y"),
    url(r'provider/action/$', ProviderActionView.as_view(), name="provider_action"),
    url(r'provider/map/$', ProviderMapView.as_view(), name="provider_map"),

    # url(r'^login$', LoginView.as_view(), name="login"),
    # url(r'^create/$',  CustomerCreateView.as_view(), name="create"),
    # url(r'^detail/(?P<pk>\d+)/$',  CustomerDetailView.as_view(), name="details"),
    # url(r'^update/(?P<pk>\d+)/$',  CustomerUpdateView.as_view(), name="update"),
    # url(r'^delete/(?P<pk>\d+)/$',  CustomerDeleteView.as_view(), name="delete"),
]

smart_waste/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('app.urls')),

]

app/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser


class MyUser(AbstractUser):
    is_customer = models.BooleanField(default=True)
    credits = models.FloatField(default=0)
    address = models.TextField(null=True, blank=True)
    phoneno = models.CharField(null=True, blank=True, max_length=100)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    place_id = models.CharField(max_length=64, blank=True, null=True)
    rating = models.IntegerField(default=1)


class Orders(models.Model):
    """
    Model to store order details
    """
    WASTE_CATEGORY = (
        ('O', 'Organic Waste'),
        ('P', 'Paper waste'),
        ('L', 'Plastic waste'),
        ('S', 'Scrap waste'),
        ('G', 'Glass waste'),
    )
    WASTE_SIZE = (
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
    )
    REQUEST_STATUS = (
        ('P', 'Pending'),
        ('A', 'Accepted'),
        ('R', 'Rejected')
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='user_orders',
        on_delete=models.CASCADE
    )
    waste_category = models.CharField(max_length=1, choices=WASTE_CATEGORY)
    waste_size = models.CharField(max_length=1, choices=WASTE_SIZE)
    comments = models.TextField(blank=True, null=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    place_id = models.CharField(max_length=64, blank=True, null=True)
    request_status = models.CharField(max_length=1, choices=REQUEST_STATUS, default='P')

    provider = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='user_provider',
        on_delete=models.CASCADE, null=True, blank=True
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)




class Test(models.Model):
    """
    Model to store order details
    """
    WASTE_CATEGORY = (
        ('A', 'Accept'),
        ('P', 'Pending'),
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='user_orders_test',
        on_delete=models.CASCADE
    )
    waste_category = models.CharField(max_length=1, choices=WASTE_CATEGORY,default='P')
    comments = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

templates/app/add_workflow.html
{% extends "base.html" %}

{% block content %}
<div class="pcoded-content">
      <div class="pcoded-inner-content">
          <div class="main-body">
              <div class="page-wrapper">
                  <div class="page-body">
                      <div class="row">
                          <div class="tool-box">
                            <div class="action-type" draggable="true" data-order="0" data-type="flight"
                                 data-toggle="tooltip" title="Select your flight" data-nb-inputs="1" data-nb-outputs="1">
                              <span class="tool-item pcoded-micon">
                                <i class="fa fa-plane c-2" >
                                </i>
                              </span>
                            </div>
                            <div class="action-type" draggable="true" data-order="1" data-type="hotel"
                            data-nb-inputs="1" data-nb-outputs="1">
                                <span class="tool-item pcoded-micon">
                                  <i class="fa fa-hotel c-3" aria-hidden="true"
                                  data-toggle="tooltip" title="Select your hotel"></i>
                                </span>
                            </div>
                            <div class="action-type" draggable="true" data-order="6" data-type="cars"
                            data-nb-inputs="1" data-nb-outputs="1">
                                <span class="tool-item pcoded-micon">
                                  <i class="fa fa-car c-1" aria-hidden="true"
                                  data-toggle="tooltip" title="Select your cab"></i>
                                </span>
                            </div>
                            <div class="action-type" draggable="true" data-order="1" data-type="approve"
                            data-nb-inputs="1" data-nb-outputs="1">
                                <span class="tool-item pcoded-micon">
                                  <i class="fa fa fa-check-square-o c-4" aria-hidden="true"
                                  data-toggle="tooltip" title="Approval"></i>
                                </span>
                            </div>
                            <div class="action-type" draggable="true" data-order="1" data-type="ticket"
                            data-nb-inputs="1" data-nb-outputs="1">
                                <span class="tool-item pcoded-micon" >
                                  <i class="fa fa-ticket c-5" aria-hidden="true"
                                  data-toggle="tooltip" title="Ticketing"></i>
                                </span>
                            </div>
                            <div class="action-type" draggable="true" data-order="1" data-type="file"
                            data-nb-inputs="1" data-nb-outputs="1">
                                <span class="tool-item pcoded-micon">
                                  <i class="fa fa-file-o c-6" aria-hidden="true"
                                  data-toggle="tooltip" title="Upload your receipts"></i>
                                </span>
                            </div>
                            <div class="action-type" draggable="true" data-order="1" data-type="money"
                            data-nb-inputs="1" data-nb-outputs="1">
                                <span class="tool-item pcoded-micon">
                                  <i class="fa fa-money c-7" aria-hidden="true"
                                  data-toggle="tooltip" title="Finance review"></i>
                                </span>
                            </div>
                            <div class="action-type" draggable="true" data-order="2" data-type="close"
                            data-nb-inputs="1" data-nb-outputs="0">
                                <span class="tool-item pcoded-micon">
                                  <i class="fa fa-hand-paper-o c-8" aria-hidden="true"
                                  data-toggle="tooltip" title="Close"></i>
                                </span>
                            </div>
                            <div class="action-type" draggable="true" data-order="4" data-type="wifi"
                            data-nb-inputs="1" data-nb-outputs="0">
                                <span class="tool-item pcoded-micon">
                                  <i class="fa fa-wifi" aria-hidden="true"
                                  data-toggle="tooltip" title="Add wifi"></i>
                                </span>
                            </div>

                            <div class="action-type" draggable="true" data-order="5" data-type="cutlery"
                            data-nb-inputs="1" data-nb-outputs="1">
                                <span class="tool-item pcoded-micon">
                                  <i class="fa fa-cutlery"
                                  data-toggle="tooltip" title="Add extra food"></i>
                                </span>
                            </div>

                              <div class="action-type" draggable="true" data-order="4" data-type="visa"
                              data-nb-inputs="1" data-nb-outputs="1">
                                <span class="tool-item pcoded-micon">
                                  <i class="fa fa-file-text" aria-hidden="true"
                                  data-toggle="tooltip" title="Apply visa"></i>
                                </span>
                            </div>
                            <div class="tool_delete delete_selected_button" draggable="true"
                            data-nb-inputs="1" data-nb-outputs="1">
                                <span class="tool-item pcoded-micon">
                                  <i class="fa fa-trash-o c-9"
                                  data-toggle="tooltip" title="Delete selected item"></i>
                                </span>
                            </div>

                          </div>
                      </div>
                      <div class="row">
                          <div class="col-xl-9 col-md-18 draw-board">
                            <div class="draw-board-inner" id="example">
                            </div>
                          </div>
                          <div class="col-xl-3 col-md-18 price-board">
                            <div class="draw-board-inner" >
                                <div class="col-md-12 col-sm-12 m-t-25 m-d-25">
                                    <h3>Your Itinerary</h3>
                                </div>
                                <div class="col-md-12 col-sm-12  m-t-25 m-d-25">
                               <h3 style="color : green ">  David Friderici </h3>
                                </div>
                                <div class="col-md-12 col-sm-12">
                                    <ul class="price_list">
                                        <li class="row card-box">
                                            <span class="itemName item">Flight</span>
                                            <span class="price m-l-20">€ 288</span>
                                        </li>
                                        <li class="row card-box">
                                            <span class="itemName item">Hotel</span>
                                            <span class="price m-l-20">€ 509</span>
                                        </li>
                                        <li class="row card-box">
                                            <span class="itemName item">Cars &nbsp</span>
                                            <span class="price m-l-20">€ 00</span>
                                        </li>

                                        <li class="row card-box total-price" style="background-color:#7ace7a; color:white;">
                                            <span class="itemName item" style=" color:white;">Total:</span>
                                            <span class="price m-l-20" style="color:white;">€797</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                          </div>
                      </div>
                  </div>
              </div>

              <!--<div id="styleSelector">-->
              <!--</div>-->
          </div>
      </div>
</div>
{% endblock %}
{% block extra_js %}
  <script>
  {% if workflow %}
      var workflow = {{workflow | safe}};
      var approved = {% if workflow.status %} 1 {% else %} 0 {% endif %};
  {% else %}
      var workflow = 'None';
      var approved = 0;
  {% endif %}
  </script>
{% endblock %}

templates/app/confirmation.html
<div class="col-xl-12 col-md-12">
     <div class="card user-card-full ">
        <div class="row m-l-0 m-r-0">
            <div class="col-sm-3 user-profile">
                <div class="card-block text-center text-white">
                    <div class="m-b-25">
                        <img src="/static/images/logo-sun.png">
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card-block flight-route">
                    <div class="row">
                        <div class="col-sm-3 leg1">
                            <h6 class="f-w-600 ">AYT</h6>
                            <span class="time">07:10</span>
                        </div>
                        <div class="col-sm-6">
                            <span class="duration">01h 10m</span>
                            <ul class="leg-info"></ul>
                            <img src="/static/images/download.svg" class="flight-img">
                        </div>
                        <div class="col-sm-3 leg1">
                            <h6 class=" f-w-600 ">FRA</h6>
                            <span class="time">08:20</span>
                        </div>
                    </div>
                </div>

                <div class="card-block flight-route">
                    <div class="row">
                        <div class="col-sm-3 leg1">
                            <h6 class="f-w-600 ">FRA</h6>
                            <span class="time">11:35</span>
                        </div>
                        <div class="col-sm-6">
                            <span class="duration">02h 25m</span>
                            <ul class="leg-info"></ul>
                            <img src="/static/images/download.svg" class="flight-img">
                        </div>
                        <div class="col-sm-3 leg1">
                            <h6 class=" f-w-600 ">AYT</h6>
                            <span class="time">14:00</span>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-sm-5 divider">
                <div class="row">
                    <div class="col-sm-8">
                        <ul class="ancillaries">

                             <li><i class="ext-seat m-r-10" style="color :red; background:url('/static/images/ext-seat.svg')"></i></li>
                                                <li><i class="fa fa-suitcase  m-r-10" style="color:green;" aria-hidden="true"></i></li>
                                                <li><i class="fa fa-tablet m-r-10" style="color:green;" aria-hidden="true"></i></li>
                                                <li><i class="fa fa-television m-r-10"  style="color:green;"aria-hidden="true"></i></li>
                                                <li><i class="fa fa-wifi m-r-10" style="color:green;" aria-hidden="true"></i></li>
                        </ul>
                    </div>
                    <div class="col-sm-4">
                        <div class="price">
                            <p class="m-b-10 f-w-600">Price 267.988 €</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="col-xl-12 col-md-12">
     <div class="card user-card-full ">
        <div class="row m-l-0 m-r-0">
            <div class="col-sm-4 bg-c-blue user-profile" style="background:url(https://d2xf5gjipzd8cd.cloudfront.net/available/330851624/rmca.jpg)">
                <div class="card-block text-center text-white">
                    <div class="m-b-25">
                    </div>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="card-block">
                    <h6 class="m-b-20 p-b-5  f-w-600">Sheraton Frankfurt Airport Hotel and Conference Center</h6>

                    <div class="row">
                        <div class="col-sm-6">
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                        </div>
                    </div>

                        <div class="row">
                        <div class="col-sm-12">
                            <p class="m-b-10 f-w-600">Based on 11208 reviews</p>
                        </div>
                        </div>


                </div>
            </div>

            <div class="col-sm-3">
                <div class="price">
                    <p class="m-b-10 f-w-600 ">Price 509 €</p>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="col-xl-12 col-md-12">
     <div class="card user-card-full ">
        <div class="row m-l-0 m-r-0">
            <div class="col-sm-12">
                <div class="price">
                    <p class="m-b-10 f-w-600 ">Total 797 €</p>
                </div>
            </div>
        </div>
    </div>
</div>

<button class="btn btn-primary pull-right">
    Verified
</button>

templates/app/hotels.html
{% load static %}
<div class="row">
      {% for hotel in hotels %}
          <div class="col-xl-6 col-md-12">
                 <div class="card user-card-full {% if 'selected' in hotel %} selected {% endif %}">
                    <div class="row m-l-0 m-r-0">
                        <div class="col-sm-4 bg-c-blue user-profile" style="background:url({{hotel.images.0.gallery}})">
                            <div class="card-block text-center text-white">
                                <div class="m-b-25">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="card-block">
                                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">{{hotel.name}}</h6>

                                <div class="row">
                                    <div class="col-sm-6">
                                        <span class="fa fa-star checked"></span>
                                        <span class="fa fa-star checked"></span>
                                        <span class="fa fa-star checked"></span>
                                        <span class="fa fa-star"></span>
                                        <span class="fa fa-star"></span>
                                    </div>
                                </div>

                                    <div class="row">
                                    <div class="col-sm-12">
                                        <p class="m-b-10 f-w-600">Based on {{hotel.reviews_count}} reviews</p>
                                    </div>
                                    </div>

                                <div class="row">
                                    <div class="col-sm-12">
                                        <p class="m-b-10 f-w-600">Price {{hotel.offers.0.price}} &euro;</p>
                                        <button class="btn btn-primary pull-right">
                                            {% if 'selected' in hotel %} selected {% else %}
                                            select
                                            {% endif %}
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
          </div>
    {% endfor %}
  </div>

templates/app/test.html
<!DOCTYPE html>
<html>
<head>
    <title>Page Title</title>
</head>
<body>

<h1>This is a Heading</h1>
<p>This is a paragraph.</p>

<form name="myform" action="{% url 'customer_order' %}" method="POST">
    {% csrf_token %}
    <div align="center">
        <select name="waste_category">
            <option value="O">Organic Waste</option>
            <option value="P">Paper waste</option>
        </select>
    </div>

    <input type="text" name="comments" value="">
    <br><br>
    <input type="submit" value="Submit">
</form>

</body>
</html>

templates/app/user_orders.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="pcoded-content">
    <div class="pcoded-inner-content">
          <div class="main-body">
              <div class="page-wrapper">
                  <div class="page-body">

                      {% for order in orders %}
                        <div class="row">
                              <div class="col-sm-12 col-md-12">
                                     <div class="card user-card-full ">
                                        <div class="row m-l-0 m-r-0">
                                            <div class="col-sm-2 user-profile" >
                                                <div class="card-block text-center text-white">
                                                    <div class="1">
                                                        {% if order.waste_category == "P" %}
                                                        <img class="d-flex align-self-center img-radius" style="width:75px;" src="{% static "open-book.png" %}" alt="Generic placeholder image">

                                                        {% elif order.waste_category == "L"%}
                                                        <img class="d-flex align-self-center img-radius" style="width:75px;" src="{% static "botl.png" %}" alt="Generic placeholder image">

                                                        {% elif order.waste_category == "O"%}
                                                        <img class="d-flex align-self-center img-radius" style="width:75px;" src="{% static "bananas.png" %}" alt="Generic placeholder image">

                                                        {% elif order.waste_category == "S"%}
                                                        <img class="d-flex align-self-center img-radius" style="width:75px;" src="{% static "screw.png" %}" alt="Generic placeholder image">

                                                        {% elif order.waste_category == "G"%}
                                                        <img class="d-flex align-self-center img-radius" style="width:75px;" src="{% static "glass.png" %}" alt="Generic placeholder image">

                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-10">
                                                <div class="card-block">
                                                    <h6 class="m-b-20 p-b-2 b-b-default f-w-600">{{ order.provider.get_username |title }}
                                                        <div class="col-sm-6 rating">
                                                            <span class="fa fa-star checked"></span>
                                                            <span class="fa fa-star checked"></span>
                                                            <span class="fa fa-star checked"></span>
                                                            <span class="fa fa-star"></span>
                                                            <span class="fa fa-star"></span>
                                                        </div>
                                                    </h6>
                                                    <div class="row">
                                                        {% if order.provider %}
                                                        <div class="col-sm-12">
                                                            <span class="m-b-10 f-w-600">
                                                                {% if order.waste_size == "S" %}
                                                                <i class="fa fa-shopping-bag" aria-hidden="true"></i>
                                                                {% elif order.waste_size == "M" %}
                                                                <i class="fa fa-shopping-basket" aria-hidden="true"></i>
                                                                {% elif order.waste_size == "L" %}
                                                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                                                {% endif %}

                                                                <!--Waster Size : order.provider-->
                                                            </span>
                                                            <br>
                                                            <span class="m-b-10 f-w-600">Phone no: {{ order.provider.phoneno }}</span>
                                                             <span class="m-b-10 f-w-100 distance">
                                                                 <i class="fa fa-map-marker" aria-hidden="true" style="color:orange"></i>
                                                                 10 km away</span>
                                                        </div>
                                                        {% endif %}
                                                    </div>

                                                    <div class="row">
                                                        <div class="col-sm-12">
                                                            <i class="btn btn-primary pull-right">
                                                                {{order.get_request_status_display}}
                                                            </i>

                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                              </div>
                        </div>
                      {% endfor %}
                        </div>
                    </div>
                </div>
          </div>
  </div>
{% endblock %}

templates/app/workflow_list.html
{% extends "base.html" %}
{% load static %}
{% block extra_style %}
  <link rel="stylesheet" type="text/css" href="{% static "files\bower_components\datatables.net-bs4\css\dataTables.bootstrap4.min.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "files\assets\pages\data-table\css\buttons.dataTables.min.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "files\bower_components\datatables.net-responsive-bs4\css\responsive.bootstrap4.min.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "files\assets\pages\data-table\extensions\responsive\css\responsive.dataTables.css" %}">
{% endblock %}
{% block content %}
<div class="pcoded-content">
      <div class="pcoded-inner-content">
          <div class="main-body">
              <div class="page-wrapper">
                  <div class="page-body">
                    <div class="card">
                        <div class="card-header">
                            <h5>Schema</h5>
                            <div class="card-header-right">
                                <ul class="list-unstyled card-option">
                                    <li><i class="feather icon-maximize full-card"></i></li>
                                    <li><i class="feather icon-minus minimize-card"></i></li>
                                    <li><i class="feather icon-trash-2 close-card"></i></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-block">
                            <div class="table-responsive">
                                <div class="dt-responsive table-responsive">
                                    <table id="res-config" class="table table-striped table-bordered nowrap">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Last name</th>
                                                <th>Position</th>
                                                <th>Office</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for schema in schema_list %}
                                            <tr>
                                                <td>{{schema.name}}</td>
                                                <td>Nixon</td>
                                                <td>System Architect</td>
                                                <td>Edinburgh</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                  </div>
              </div>
          </div>
      </div>
</div>

{% endblock %}